### ISSUE TITLE
Missing titles and MetaData from certain routes

### ISSUE THREAD

**Issue by Deas-Dose** [LazyClicks/first-qwik-project#1]
I was checking this repo and it turned out to be missing some titles from `contact` and `about` pages, also missing some SEO stuff (meta tags), hope this gets fixed. 

Keep up the good work.

**Comment by LazyClicks** [comment]
Hello, thank you for the advice.
im still in the process of learning qwik so i didn't pay much attention to seo, but still thank you.
was not expecting an issue in this one lol
